"""fix chat_messages.created_at server default

Revision ID: 56bc761ce45a
Revises: fb2f83897f85
Create Date: 2026-08-21 13:39:39.583443
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '56bc761ce45a'
down_revision: Union[str, None] = 'fb2f83897f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-21 13:37:01.555986+05:30'::timestamp with time zone"),
               existing_nullable=False)
    # ### end Alembic commands ###
