"""release 2 multi-tenancy

Revision ID: 56cebd87d211
Revises: 56bc761ce45a
Create Date: 2026-08-29 23:20:54.948195
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '56cebd87d211'
down_revision: Union[str, None] = '56bc761ce45a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ------------------------------------------------------------------ #
    # Release 1 document and chat data is removed before the tenant columns
    # are added.
    #
    # Approved explicitly ("old document data can be deleted"), and it is what
    # lets organization_id be added as NOT NULL in a single step instead of
    # add-nullable / backfill / alter-not-null. Children first:
    # message_sources holds ON DELETE RESTRICT on documents, so deleting
    # documents while a citation exists would fail.
    #
    # The Qdrant `documents` collection is dropped separately by
    # scripts/release2_reset_vectors.py - a database migration cannot reach it.
    # ------------------------------------------------------------------ #
    for table in (
        "message_sources",
        "chat_messages",
        "conversations",
        "document_chunks",
        "document_tags",
        "document_processing",
        "documents",
    ):
        op.execute(f"DELETE FROM {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='organization_status'), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('max_documents', sa.Integer(), nullable=True),
    sa.Column('max_document_size_mb', sa.Integer(), nullable=True),
    sa.Column('rate_limit_chat', sa.String(length=32), nullable=True),
    sa.Column('rate_limit_upload', sa.String(length=32), nullable=True),
    sa.Column('rate_limit_public_chat', sa.String(length=32), nullable=True),
    sa.Column('public_chat_enabled', sa.Boolean(), nullable=False),
    sa.Column('public_chat_key', sa.String(length=64), nullable=False),
    sa.Column('public_chat_greeting', sa.String(length=500), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_public_chat_key'), 'organizations', ['public_chat_key'], unique=True)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('organization_admins',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_admins_email'), 'organization_admins', ['email'], unique=True)
    op.create_index(op.f('ix_organization_admins_mobile'), 'organization_admins', ['mobile'], unique=True)
    op.create_index(op.f('ix_organization_admins_organization_id'), 'organization_admins', ['organization_id'], unique=False)
    op.create_table('otp_requests',
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('identifier_type', sa.Enum('EMAIL', 'MOBILE', name='identifier_type'), nullable=False),
    sa.Column('organization_admin_id', sa.UUID(), nullable=True),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_admin_id'], ['organization_admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_requests_identifier'), 'otp_requests', ['identifier'], unique=False)
    op.create_index('ix_otp_requests_identifier_created', 'otp_requests', ['identifier', 'created_at'], unique=False)
    op.create_index(op.f('ix_otp_requests_organization_admin_id'), 'otp_requests', ['organization_admin_id'], unique=False)
    # add_column does not create the enum type the way create_table does, so it
    # is created explicitly here or the ALTER fails on an undefined type.
    actor_type = sa.Enum('SUPER_ADMIN', 'ORG_ADMIN', 'SYSTEM', name='audit_actor_type')
    actor_type.create(op.get_bind(), checkfirst=True)
    op.add_column('audit_logs', sa.Column('actor_type', actor_type, nullable=True))
    op.add_column('audit_logs', sa.Column('super_admin_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('organization_admin_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.create_index('ix_audit_logs_org_created', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index('ix_audit_logs_super_admin_created', 'audit_logs', ['super_admin_id', 'created_at'], unique=False)
    op.drop_constraint('audit_logs_user_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key('fk_audit_logs_super_admin_id', 'audit_logs', 'users', ['super_admin_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_audit_logs_organization_id', 'audit_logs', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_audit_logs_organization_admin_id', 'audit_logs', 'organization_admins', ['organization_admin_id'], ['id'], ondelete='SET NULL')
    op.drop_column('audit_logs', 'user_id')
    op.add_column('conversations', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.add_column('conversations', sa.Column('organization_admin_id', sa.UUID(), nullable=True))
    op.add_column('conversations', sa.Column('visitor_session_id', sa.String(length=64), nullable=True))
    op.drop_index('ix_conversations_user_last_message', table_name='conversations')
    op.create_index('ix_conversations_org_admin', 'conversations', ['organization_id', 'organization_admin_id'], unique=False)
    op.create_index('ix_conversations_org_last_message', 'conversations', ['organization_id', 'last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_organization_id'), 'conversations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_conversations_visitor_session_id'), 'conversations', ['visitor_session_id'], unique=False)
    op.drop_constraint('conversations_user_id_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key('fk_conversations_organization_admin_id', 'conversations', 'organization_admins', ['organization_admin_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_conversations_organization_id', 'conversations', 'organizations', ['organization_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('conversations', 'user_id')
    # Not autogenerated - Alembic does not diff CheckConstraint. Without it a
    # conversation could end up owned by neither an admin nor a visitor:
    # invisible to every ownership query, and to cleanup.
    op.create_check_constraint(
        "ck_conversations_single_owner",
        "conversations",
        "(organization_admin_id IS NOT NULL AND visitor_session_id IS NULL)"
        " OR (organization_admin_id IS NULL AND visitor_session_id IS NOT NULL)",
    )
    op.add_column('document_chunks', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_document_chunks_organization_id'), 'document_chunks', ['organization_id'], unique=False)
    op.create_foreign_key('fk_document_chunks_organization_id', 'document_chunks', 'organizations', ['organization_id'], ['id'], ondelete='RESTRICT')
    op.add_column('documents', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.add_column('documents', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.drop_index('ix_documents_created_at', table_name='documents')
    op.drop_index('ix_documents_status_deleted', table_name='documents')
    op.create_index('ix_documents_org_created', 'documents', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_documents_org_public', 'documents', ['organization_id', 'is_public'], unique=False)
    op.create_index('ix_documents_org_status_deleted', 'documents', ['organization_id', 'status', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.drop_constraint('documents_created_by_fkey', 'documents', type_='foreignkey')
    op.create_foreign_key('fk_documents_created_by', 'documents', 'organization_admins', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_documents_organization_id', 'documents', 'organizations', ['organization_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint("ck_conversations_single_owner", "conversations", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documents_created_by', 'documents', type_='foreignkey')
    op.drop_constraint('fk_documents_organization_id', 'documents', type_='foreignkey')
    op.create_foreign_key('documents_created_by_fkey', 'documents', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index('ix_documents_org_status_deleted', table_name='documents')
    op.drop_index('ix_documents_org_public', table_name='documents')
    op.drop_index('ix_documents_org_created', table_name='documents')
    op.create_index('ix_documents_status_deleted', 'documents', ['status', 'deleted_at'], unique=False)
    op.create_index('ix_documents_created_at', 'documents', ['created_at'], unique=False)
    op.drop_column('documents', 'is_public')
    op.drop_column('documents', 'organization_id')
    op.drop_constraint('fk_document_chunks_organization_id', 'document_chunks', type_='foreignkey')
    op.drop_index(op.f('ix_document_chunks_organization_id'), table_name='document_chunks')
    op.drop_column('document_chunks', 'organization_id')
    op.add_column('conversations', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_conversations_organization_admin_id', 'conversations', type_='foreignkey')
    op.drop_constraint('fk_conversations_organization_id', 'conversations', type_='foreignkey')
    op.create_foreign_key('conversations_user_id_fkey', 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_conversations_visitor_session_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_organization_id'), table_name='conversations')
    op.drop_index('ix_conversations_org_last_message', table_name='conversations')
    op.drop_index('ix_conversations_org_admin', table_name='conversations')
    op.create_index('ix_conversations_user_last_message', 'conversations', ['user_id', 'last_message_at'], unique=False)
    op.drop_column('conversations', 'visitor_session_id')
    op.drop_column('conversations', 'organization_admin_id')
    op.drop_column('conversations', 'organization_id')
    op.add_column('audit_logs', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_audit_logs_super_admin_id', 'audit_logs', type_='foreignkey')
    op.drop_constraint('fk_audit_logs_organization_id', 'audit_logs', type_='foreignkey')
    op.drop_constraint('fk_audit_logs_organization_admin_id', 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_user_id_fkey', 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_audit_logs_super_admin_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_created', table_name='audit_logs')
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.drop_column('audit_logs', 'organization_id')
    op.drop_column('audit_logs', 'organization_admin_id')
    op.drop_column('audit_logs', 'super_admin_id')
    op.drop_column('audit_logs', 'actor_type')

    op.drop_index(op.f('ix_otp_requests_organization_admin_id'), table_name='otp_requests')
    op.drop_index('ix_otp_requests_identifier_created', table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_identifier'), table_name='otp_requests')
    op.drop_table('otp_requests')
    op.drop_index(op.f('ix_organization_admins_organization_id'), table_name='organization_admins')
    op.drop_index(op.f('ix_organization_admins_mobile'), table_name='organization_admins')
    op.drop_index(op.f('ix_organization_admins_email'), table_name='organization_admins')
    op.drop_table('organization_admins')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_public_chat_key'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###

    # LAST. drop_table does not drop the enum types create_table made. Leaving them
    # behind makes the next upgrade fail on "type already exists", so a
    # downgrade that cannot be re-upgraded is not a downgrade.
    for enum_name in ('audit_actor_type', 'identifier_type', 'organization_status'):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
